name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.23"
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.1
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.23"
      - name: Go Test
        run: go test -v ./...
